title: Liberty Church, Newport, South Wales
description: As a local church we are a community of everyday people in which Jesus is central, in all we do, as we seek to embrace our city and nation we live in.
url: https://libertychurchuk.github.io
author: Liberty Church
twitter:
  username: LibertyChurchUK
facebook:
 app_id:
 publisher:
 admins:
logo: /images/og-default.jpg
lang: en-GB

# Pagination settings
paginate: 10

# SCSS Output
sass:
  style: :compressed

# Additional Jekyll Support
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
