title: Liberty Church, Newport, South Wales
short_title: Liberty Church
description: As a local church we are a community of everyday people in which Jesus is central, in all we do, as we seek to embrace our city and nation we live in.
url: http://www.libertychurchuk.com
theme_color: '#0b7ca2'
background_color: '#1f1f1f'

author:
  name: Liberty Church

# Pagination settings
paginate: 10

# SCSS Output
sass:
  style: :compressed

# Additional Jekyll Support
gems:
  - jekyll-sitemap
