---
title: Liberty Church, Newport, South Wales
subtitle: Liberty Church UK
timezone: UTC
collections:
  testimonies:
    title: Testimony
    output: true
    permalink: "/testimony/:year/:month/:day/:title/"
  devotionals:
    title: Devotional
    output: true
    permalink: "/devotionals/:year/:month/:day/:title/"
  groups:
    title: Groups
    output: false
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  posts:
    title: Posts
    output: true
    permalink: "/blog/:year/:month/:day/:title/"
  messages:
    title: Messages
    output: true
    permalink: "/messages/:path/"
  studies:
    title: Studies
    output: true
    permalink: "/bible-studies/:path/"
  series:
    title: Series
    output: true
    permalink: "/series/:path/"
  banners:
    title: Banners
    output: false
  alerts:
    title: Alerts
    output: false
defaults:
- scope:
    path: ''
    type: messages
  values:
    layout: message
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: testimonies
  values:
    layout: testimony
- scope:
    path: ''
    type: devotionals
  values:
    layout: devotional
- scope:
    path: ''
    type: studies
  values:
    layout: study
- scope:
    path: ''
    type: series
  values:
    layout: series
- scope:
    path: ''
    type: authors
  values:
    layout: authors
description: As a local church we are a community of everyday people in which Jesus
  is central, in all we do, as we seek to embrace our city and nation we live in.
url: https://www.libertychurchuk.com
author: Liberty Church
email: web@libertychurchuk.com
twitter:
  username: LibertyChurchUK
facebook:
  app_id: 
  publisher: 
  admins: 
logo: "/assets/images/logos/liberty-church-logo.png"
lang: en-GB
social:
  links:
  - https://twitter.com/LibertyChurchUK
  - https://www.facebook.com/libertychurchfamily
  - https://instagram.com/libertychurchuk
  - https://vimeo.com/libertychurchuk
cloudinary_url: https://res.cloudinary.com/libertychurchuk/image/upload
copyright: Copyright © 2020 Liberty Church. All rights reserved.
charity: Liberty Church is a registered charity in England and Wales 1161640
contact:
  email: hello@libertychurchuk.com
  telephone: '07943 501007'
  service-time: 9.30am and 11am
  service-address: Gaer Christian Centre, Gaer Park Drive, Newport, NP20 3NN, United
    Kingdom
  admin-address: 42 Bryngwyn Road, Newport, NP20 4JT, United Kingdom
pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: "12"
  permalink: "/page:num/"
  title: ":title - page :num"
  limit: "0"
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: "2"
    after: "2"
  extension: html
  indexpage: index
sass:
  style: ":compressed"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate-v2
- jekyll-menus
