title: Liberty Church, Newport, South Wales
short_title: Liberty Church
description: A family church in Newport that loves Jesus
url: http://www.libertychurchuk.com
theme_color: '#0b7ca2'
background_color: '#1f1f1f'


author:
  name: Richard Saunders
  url: https://www.rdsaunders.co.uk
  email: noreply@rdsaunders.co.uk
  photo: https://gravatar.com/avatar/6747ba6c061b6886d3d4b3aafd82ac7d?s=256
