---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Podcast
- type: directory
  path: _messages
  label: Messages
  create: documents
  match: "**/*"
  templates:
  - message
- type: directory
  path: _series
  label: Message Series
  create: documents
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: _posts
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: _testimonies
  label: Testimonies
  create: documents
  match: "**/*"
  templates:
  - this-is-my-story-alice
- type: directory
  path: _authors
  label: People
  create: documents
  match: "**/*"
  templates:
  - author
- type: jekyll-pages
  label: Pages
  create: documents
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
custom_preview: true
