---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Podcast
- type: directory
  path: _messages
  label: Messages
  create: documents
  match: "**/*"
  templates:
  - message
- type: directory
  path: _series
  label: Message Series
  create: documents
  match: "**/*"
- type: heading
  label: Structured content
- type: directory
  path: _banners
  label: Banners
  create: documents
  match: "**/*"
  templates:
  - banner
- type: directory
  path: _posts
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: _devotionals
  label: Devotionals
  create: documents
  match: "**/*"
  templates:
  - devotional
- type: directory
  path: _groups
  label: Liberty groups
  create: documents
  match: "**/*"
  templates:
  - liberty-group
- type: directory
  path: _authors
  label: People
  create: documents
  match: "**/*"
  templates:
  - author
- type: directory
  path: _testimonies
  label: Testimonies
  create: documents
  match: "**/*"
  templates:
  - this-is-my-story-alice
- type: heading
  label: Pages
- type: jekyll-pages
  label: Pages
  create: documents
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: ''
public_path: https://res.cloudinary.com/libertychurchuk/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_command: bundle exec jekyll serve --port 8080 --host 0.0.0.0.
