---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _posts
  label: Blog
  create: documents
  match: "**/*"
- type: directory
  path: _testimonies
  label: Testimonies
  create: documents
  match: "**/*"
- type: directory
  path: _messages
  label: Messages
  create: documents
  match: "**/*"
- type: directory
  path: _authors
  label: People
  create: documents
  match: "**/*"
  templates:
  - author
- type: jekyll-pages
  label: Pages
  create: documents
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:, :month:, :day:, :filename:"
